console.log("Hello World");
var Number = "299792458";
console.log(Number);
console.log(typeof Number);
var strType = `Akib Basri`;
console.log(typeof strType);
var myName = 'Akib Basri';
console.log(myName);
var numType = 30;
console.log(numType);
console.log(typeof numType);
var bul = true;
console.log(typeof bul);
var Goru = "baal saal jodu modu kodu";
console.log(Goru.toLowerCase());
var Srs = "A B C D";
console.log(Srs.split("B"));
console.log(Srs.indexOf("C"));
var num1 = 100;
var num2 = 26;
var mot = num1 + num2;
console.log(mot);
var num3 = "55";
var num3 = parseFloat(num3);;
var num4 = 5
// num4 = "" + num4;
console.log(typeof num3);
console.log(num3 / num4);
console.log(num3 * num4);
var num5 = 60;
var num6 = 70;
console.log(num6 % num5);